### ISSUE TITLE
dark theme 

### ISSUE THREAD

**Issue by Nithin552** [itstommi/Spotify-Readme#1]
can you make available rainbow equalizer for dark theme too?

**Comment by itstommi** [comment]
It is, just use `/api?dark=true&rainbow=true`

**Comment by Nithin552** [comment]
yeah i configured...but why did you set recently played limit to only 1??only 1 song is refreshing from list

**Comment by itstommi** [comment]
That’s just what I prefer. You can change it in your own repo if you want to.

**Comment by Nithin552** [comment]
will this sort out & update the recently played list?

**Comment by Nithin552** [comment]
i made pull request about that issue

**Comment by itstommi** [comment]
It isn’t an issue in my eyes. I made the limit just one so it won’t randomly change the song if you’re not playing anything on Spotify if that makes sense.

**Comment by Nithin552** [comment]
hey cool i understood what you mean based on the previous Spotify real-time versions your vesrion is quite unfamiliar that songs may randomly change in recently played tracks so i made a PR as you mentioned earlier in your repo thanks for your suggestion
