### ISSUE TITLE
I am getting an Error 404

### ISSUE THREAD

**Issue by jaivardhan-bhola** [itstommi/Spotify-Readme#5]

**Comment by jaivardhan-bhola** [comment]
![image](https://user-images.githubusercontent.com/83286825/163844243-00b7e158-dba0-40d9-8ed1-6202a2eb2544.png)

**Comment by itstommi** [comment]
Please make sure you're using the `/api` endpoint

**Comment by jaivardhan-bhola** [comment]
could you tell me what I am doing wrong?
![image](https://user-images.githubusercontent.com/83286825/164243548-218bf0e7-a826-4634-9e9c-868f6ab001f6.png)

**Comment by itstommi** [comment]
What is the url of your project?

**Comment by jaivardhan-bhola** [comment]
https://github.com/jaivardhan-bhola/Spotify-Readme

**Comment by itstommi** [comment]
What is the Vercel url?

**Comment by jaivardhan-bhola** [comment]
https://spotify-readme-rust.vercel.app

**Comment by itstommi** [comment]
Please go to this url: https://spotify-readme-rust.vercel.app/api and then check the logs to see what the error is.

**Comment by jaivardhan-bhola** [comment]
![image](https://user-images.githubusercontent.com/83286825/168411837-e2f623e1-468e-4710-bc1b-844c901170e0.png)

**Comment by legendlife** [comment]
having the same error any fixes for this @itstommi ?
